# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"nix": "20_Examples.ipynb",
         "wirdAngezeigt": "20_Examples.ipynb",
         "stdConfig": "30_CodeExample.ipynb",
         "Klauswert": "30_CodeExample.ipynb"}

modules = ["examples.py",
           "klauswert.py"]

doc_url = "https://urspb.github.io/wdkbsp/"

git_url = "https://github.com/urspb/wdkbsp/tree/master/"

def custom_doc_links(name): return None
