# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hi": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://urspb.github.io/wdkbsp/"

git_url = "https://github.com/urspb/wdkbsp/tree/master/"

def custom_doc_links(name): return None
