# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

<<<<<<< HEAD
index = {"hi": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://urspb.github.io/wdkbsp/"

git_url = "https://github.com/urspb/wdkbsp/tree/master/"
=======
index = {}

modules = []

doc_url = "https://urspb.github.io/wdkbsp/"

git_url = "https://github.com/urspb/wdkbsp/tree/{branch}/"
>>>>>>> 2226509679571d1c57d29f0482fbcec3e42346c8

def custom_doc_links(name): return None
