# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

<<<<<<< HEAD
__all__ = ['hi']

# Cell
def hi():
    return 'Hi There!'
=======
__all__ = []
>>>>>>> 2226509679571d1c57d29f0482fbcec3e42346c8
